### ISSUE TITLE
This doesnt work.. Geting an error on Fiddler 4. 

### ISSUE THREAD

**Issue by krishnakanthpps** [abstracta/ScriptGenerator#6]
Got the below error on Fiddler 4. Created two scripts and ran the following command 

Abstracta.ScriptGeneratorCLI_4.5.exe -h newtours.demoaut.com -p 80 -f E:\Test\ScriptGenerator1.saz -f E:\Test\ScriptGenerator2.saz -o E:\Test\

Executing ScriptGeneratorCLI_4._5 (Create JMeter/OpenSTA scripts based on Fiddler sessions.):

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Abstracta.Generators.Framework.JMeterGenerator.PageRequest.WriteHTTPSample  (XmlWriter xmlWriter, AbstractStep myStep, Session request, Page page, String fullURL, IEnumerable`1 validations, IEnumerable`1 parametersToExtract, Boolean followRedirects, Boolean enable, Boolean isPrimary)
   at Abstracta.Generators.Framework.JMeterGenerator.PageRequest.ToString()   at Abstracta.Generators.Framework.JMeterGenerator.Step.ToString()
   at Abstracta.Generators.Framework.JMeterGenerator.JMeterGenerator.AddThreadGroupContent(XmlWriter xmlWriter)
   at Abstracta.Generators.Framework.JMeterGenerator.JMeterGenerator.Save()
   at Abstracta.Generators.Framework.ScriptGenerator.GenerateScripts(GeneratorType generatorType)
   at ScriptGeneratorCLI_4._5.Command.Run(String[] remainingArguments)
   at ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 commands, String[] arguments, TextWriter consoleOut, Boolean skipExeInExpectedUsage)
   at ScriptGeneratorCLI_4._5.Program.Main(String[] args)

**Comment by leticiaalmeida** [comment]
H!
A www is missing in your home parameter. Please try with www.newtours.demoaut.com

Regards,
Leticia.

**Comment by krishnakanthpps** [comment]
Thanks for worked.
