### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by krishnakanthpps** [abstracta/ScriptGenerator#7]
I am trying to convert a fiddler recording for a fiddler recording. This is for a https page. 
Here is the error. 

Unhandled Exception : System.InvalidOperationException:Sequence contains no elements
at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
at Abstracta.Generators.Framework.AbstractGenerator.AbstractStep.AddRequest(Session httpReq, Page page)

Can you help?

**Comment by leticiaalmeida** [comment]
Hi! Are you using GUI generator or by command line? Could you share a capture showing the invocation? Thank you!

**Comment by krishnakanthpps** [comment]
using the CLI. it is an https site. internal site, so cant really share much info.

recorded 2 session and then trying to jmeter script from it.

**Comment by krishnakanthpps** [comment]
any help?

**Comment by sebastianlorenzo** [comment]
We need to be able to reproduce the issue in order to help you. Could you give us one case where this error happens?

Did you download the code and compiled it or are you using the .exe?

**Comment by sdeuvarow** [comment]
Hi, just to be sure.. Did u add comments to the fiddler script?

Thanks,

El 12 ago. 2016 18:29, "sebastianlorenzo" <notifications@github.com>
escribió:

We need to be able to reproduce the issue in order to help you. Could you
give us one case where this error happens?

Did you download the code and compiled it or are you using the .exe?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/abstracta/ScriptGenerator/issues/7#issuecomment-239524368>,
or mute the thread

**Comment by leticiaalmeida** [comment]
Do you try this? 
1 - Go to generator_path\trunk\Binaries .NET 4.5, 
2 - Open Abstracta.ScriptGeneratorGUI_4.5.exe 
3 - Complete the fields:
![untitled](https://cloud.githubusercontent.com/assets/8449989/17668376/5856e744-62df-11e6-972a-9db4f6b285a3.png)

**Comment by krishnakanthpps** [comment]
Tried it. It also says sequence missing.


Get Outlook for Android






On Mon, Aug 15, 2016 at 8:29 PM +0530, "leticiaalmeida" <notifications@github.com> wrote:












Do you try this? 

1 - Go to generator_path\trunk\Binaries .NET 4.5, 

2 - Open Abstracta.ScriptGeneratorGUI_4.5.exe 

3 - Complete the fields:

**Comment by krishnakanthpps** [comment]
Yes. Tried the GUI as well . It also says "Sequence contains no elements". I tried to see if there was anything that needed to put inside XML GxTest file, but could not find anything. 

I inserted comments. All I did was launch https page and then do a login. This is a secure page, so has multiple redirections. Could that be an issue. 

Even thought it just has 2 actions, but there are multiple urls and multiple redirections.

**Comment by sebastianlorenzo** [comment]
are you decrypting the HTTPs traffic captured by Fiddler?

![capture](https://cloud.githubusercontent.com/assets/8493501/17676182/b220418e-6303-11e6-9238-d7a1460725f7.PNG)

**Comment by krishnakanthpps** [comment]
I think yes. Let me check that tomorrow and provide you an update. 


Get Outlook for Android






On Tue, Aug 16, 2016 at 12:47 AM +0530, "sebastianlorenzo" <notifications@github.com> wrote:












are you decrypting the HTTPs traffic captured by Fiddler?
